//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
namespace OpcUaPars {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zat.cz/OPCUAParameters")]
    [System.Xml.Serialization.XmlRootAttribute("OPCUAParameters", Namespace="http://www.zat.cz/OPCUAParameters", IsNullable=false)]
    public partial class OPCUAParametersType {
        
        private ServerType[] serverField;
        
        private SubscriberType[] subscriberField;
        
        private PublisherType[] publisherField;
        
        private ObjectTypeType[] objectTypeField;
        
        private bool useServerField;
        
        private bool serverEncryptionField;
        
        private string serverRootTypeField;
        
        private bool useClientField;
        
        private ushort serversCountField;
        
        private bool usePublisherField;
        
        private bool publisherEncryptionField;
        
        private ushort publisherIdField;
        
        private ushort subscribersCountField;
        
        private bool useSubscriberField;
        
        private bool subscriberEncryptionField;
        
        private ushort publishersCountField;
        
        private ushort objectTypeCountField;
        
        public OPCUAParametersType() {
            this.useServerField = false;
            this.serverEncryptionField = false;
            this.serverRootTypeField = "";
            this.useClientField = false;
            this.serversCountField = ((ushort)(0));
            this.usePublisherField = false;
            this.publisherEncryptionField = false;
            this.publisherIdField = ((ushort)(0));
            this.subscribersCountField = ((ushort)(0));
            this.useSubscriberField = false;
            this.subscriberEncryptionField = false;
            this.publishersCountField = ((ushort)(0));
            this.objectTypeCountField = ((ushort)(0));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Server")]
        public ServerType[] Server {
            get {
                return this.serverField;
            }
            set {
                this.serverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Subscriber")]
        public SubscriberType[] Subscriber {
            get {
                return this.subscriberField;
            }
            set {
                this.subscriberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Publisher")]
        public PublisherType[] Publisher {
            get {
                return this.publisherField;
            }
            set {
                this.publisherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ObjectType")]
        public ObjectTypeType[] ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool UseServer {
            get {
                return this.useServerField;
            }
            set {
                this.useServerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ServerEncryption {
            get {
                return this.serverEncryptionField;
            }
            set {
                this.serverEncryptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string ServerRootType {
            get {
                return this.serverRootTypeField;
            }
            set {
                this.serverRootTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool UseClient {
            get {
                return this.useClientField;
            }
            set {
                this.useClientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(ushort), "0")]
        public ushort ServersCount {
            get {
                return this.serversCountField;
            }
            set {
                this.serversCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool UsePublisher {
            get {
                return this.usePublisherField;
            }
            set {
                this.usePublisherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool PublisherEncryption {
            get {
                return this.publisherEncryptionField;
            }
            set {
                this.publisherEncryptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(ushort), "0")]
        public ushort PublisherId {
            get {
                return this.publisherIdField;
            }
            set {
                this.publisherIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(ushort), "0")]
        public ushort SubscribersCount {
            get {
                return this.subscribersCountField;
            }
            set {
                this.subscribersCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool UseSubscriber {
            get {
                return this.useSubscriberField;
            }
            set {
                this.useSubscriberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SubscriberEncryption {
            get {
                return this.subscriberEncryptionField;
            }
            set {
                this.subscriberEncryptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(ushort), "0")]
        public ushort PublishersCount {
            get {
                return this.publishersCountField;
            }
            set {
                this.publishersCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(ushort), "0")]
        public ushort ObjectTypeCount {
            get {
                return this.objectTypeCountField;
            }
            set {
                this.objectTypeCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zat.cz/OPCUAParameters")]
    public partial class ServerType {
        
        private string descriptionField;
        
        private bool clientEncryptionField;
        
        private uint ipAddressField;
        
        private uint slaveIpAddressField;
        
        private ulong localAddressField;
        
        private string clientRootTypeField;
        
        private ushort queryPeriodField;
        
        public ServerType() {
            this.descriptionField = "";
            this.clientEncryptionField = false;
            this.ipAddressField = ((uint)(0));
            this.slaveIpAddressField = ((uint)(0));
            this.localAddressField = ((ulong)(0m));
            this.clientRootTypeField = "";
            this.queryPeriodField = ((ushort)(500));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ClientEncryption {
            get {
                return this.clientEncryptionField;
            }
            set {
                this.clientEncryptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint IpAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint SlaveIpAddress {
            get {
                return this.slaveIpAddressField;
            }
            set {
                this.slaveIpAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(ulong), "0")]
        public ulong LocalAddress {
            get {
                return this.localAddressField;
            }
            set {
                this.localAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string ClientRootType {
            get {
                return this.clientRootTypeField;
            }
            set {
                this.clientRootTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(ushort), "500")]
        public ushort QueryPeriod {
            get {
                return this.queryPeriodField;
            }
            set {
                this.queryPeriodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zat.cz/OPCUAParameters")]
    public partial class VariablesType {
        
        private string descriptionField;
        
        private string nameField;
        
        private byte typeField;
        
        private byte accessTypeField;
        
        private byte basicTypeField;
        
        private ushort arraySizeField;
        
        private string objectTypeField;
        
        public VariablesType() {
            this.descriptionField = "";
            this.nameField = "";
            this.typeField = ((byte)(0));
            this.accessTypeField = ((byte)(0));
            this.basicTypeField = ((byte)(0));
            this.arraySizeField = ((ushort)(1));
            this.objectTypeField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(byte), "0")]
        public byte Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(byte), "0")]
        public byte AccessType {
            get {
                return this.accessTypeField;
            }
            set {
                this.accessTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(byte), "0")]
        public byte BasicType {
            get {
                return this.basicTypeField;
            }
            set {
                this.basicTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(ushort), "1")]
        public ushort ArraySize {
            get {
                return this.arraySizeField;
            }
            set {
                this.arraySizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zat.cz/OPCUAParameters")]
    public partial class ObjectTypeType {
        
        private VariablesType[] variablesField;
        
        private string descriptionField;
        
        private string nameField;
        
        private ushort idField;
        
        private string baseTypeField;
        
        private ushort variablesCountField;
        
        public ObjectTypeType() {
            this.descriptionField = "";
            this.nameField = "";
            this.idField = ((ushort)(0));
            this.baseTypeField = "";
            this.variablesCountField = ((ushort)(0));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Variables")]
        public VariablesType[] Variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(ushort), "0")]
        public ushort Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string BaseType {
            get {
                return this.baseTypeField;
            }
            set {
                this.baseTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(ushort), "0")]
        public ushort VariablesCount {
            get {
                return this.variablesCountField;
            }
            set {
                this.variablesCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zat.cz/OPCUAParameters")]
    public partial class PublisherType {
        
        private string descriptionField;
        
        private ushort publisherIdField;
        
        private string subscriberRootTypeField;
        
        public PublisherType() {
            this.descriptionField = "";
            this.publisherIdField = ((ushort)(0));
            this.subscriberRootTypeField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(ushort), "0")]
        public ushort PublisherId {
            get {
                return this.publisherIdField;
            }
            set {
                this.publisherIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string SubscriberRootType {
            get {
                return this.subscriberRootTypeField;
            }
            set {
                this.subscriberRootTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zat.cz/OPCUAParameters")]
    public partial class SubscriberType {
        
        private string descriptionField;
        
        private uint ipAddressField;
        
        private uint slaveIpAddressField;
        
        private ulong localAddressField;
        
        private string publisherRootTypeField;
        
        private ushort sendPeriodField;
        
        public SubscriberType() {
            this.descriptionField = "";
            this.ipAddressField = ((uint)(0));
            this.slaveIpAddressField = ((uint)(0));
            this.localAddressField = ((ulong)(0m));
            this.publisherRootTypeField = "";
            this.sendPeriodField = ((ushort)(500));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint IpAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint SlaveIpAddress {
            get {
                return this.slaveIpAddressField;
            }
            set {
                this.slaveIpAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(ulong), "0")]
        public ulong LocalAddress {
            get {
                return this.localAddressField;
            }
            set {
                this.localAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string PublisherRootType {
            get {
                return this.publisherRootTypeField;
            }
            set {
                this.publisherRootTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(ushort), "500")]
        public ushort SendPeriod {
            get {
                return this.sendPeriodField;
            }
            set {
                this.sendPeriodField = value;
            }
        }
    }
}
