//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
namespace OpcUaCfg {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XMLSchemaOpcUa.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("cfg", Namespace="http://tempuri.org/XMLSchemaOpcUa.xsd", IsNullable=false)]
    public partial class tree {
        
        private tree_node[] tree1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tree")]
        public tree_node[] tree1 {
            get {
                return this.tree1Field;
            }
            set {
                this.tree1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XMLSchemaOpcUa.xsd")]
    public partial class tree_node {
        
        private node nodeField;
        
        private tree_node[] childrenField;
        
        /// <remarks/>
        public node node {
            get {
                return this.nodeField;
            }
            set {
                this.nodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("children")]
        public tree_node[] children {
            get {
                return this.childrenField;
            }
            set {
                this.childrenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XMLSchemaOpcUa.xsd")]
    public partial class node {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("array_var", typeof(array_var))]
        [System.Xml.Serialization.XmlElementAttribute("folder", typeof(folder))]
        [System.Xml.Serialization.XmlElementAttribute("namespace", typeof(@namespace))]
        [System.Xml.Serialization.XmlElementAttribute("simple_var", typeof(simple_var))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XMLSchemaOpcUa.xsd")]
    public partial class array_var {
        
        private node_type node_typeField;
        
        private basic_type basic_typeField;
        
        private access accessField;
        
        private kind kindField;
        
        private uint lengthField;
        
        public array_var() {
            this.node_typeField = node_type.ArrayVariable;
            this.kindField = kind.Pole;
        }
        
        /// <remarks/>
        public node_type node_type {
            get {
                return this.node_typeField;
            }
            set {
                this.node_typeField = value;
            }
        }
        
        /// <remarks/>
        public basic_type basic_type {
            get {
                return this.basic_typeField;
            }
            set {
                this.basic_typeField = value;
            }
        }
        
        /// <remarks/>
        public access access {
            get {
                return this.accessField;
            }
            set {
                this.accessField = value;
            }
        }
        
        /// <remarks/>
        public kind kind {
            get {
                return this.kindField;
            }
            set {
                this.kindField = value;
            }
        }
        
        /// <remarks/>
        public uint length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XMLSchemaOpcUa.xsd")]
    public enum node_type {
        
        /// <remarks/>
        Namespace,
        
        /// <remarks/>
        Folder,
        
        /// <remarks/>
        ObjectType,
        
        /// <remarks/>
        ObjectVariable,
        
        /// <remarks/>
        SimpleVariable,
        
        /// <remarks/>
        ArrayVariable,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XMLSchemaOpcUa.xsd")]
    public enum basic_type {
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        UInt8,
        
        /// <remarks/>
        Int8,
        
        /// <remarks/>
        UInt16,
        
        /// <remarks/>
        Int16,
        
        /// <remarks/>
        UInt32,
        
        /// <remarks/>
        Int32,
        
        /// <remarks/>
        Float,
        
        /// <remarks/>
        Double,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XMLSchemaOpcUa.xsd")]
    public enum access {
        
        /// <remarks/>
        Read,
        
        /// <remarks/>
        Write,
        
        /// <remarks/>
        ReadWrite,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XMLSchemaOpcUa.xsd")]
    public enum kind {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Jednoduchá proměnná")]
        Jednoducháproměnná,
        
        /// <remarks/>
        Pole,
        
        /// <remarks/>
        Objekt,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XMLSchemaOpcUa.xsd")]
    public partial class simple_var {
        
        private node_type node_typeField;
        
        private basic_type basic_typeField;
        
        private access accessField;
        
        private kind kindField;
        
        public simple_var() {
            this.node_typeField = node_type.SimpleVariable;
            this.kindField = kind.Jednoducháproměnná;
        }
        
        /// <remarks/>
        public node_type node_type {
            get {
                return this.node_typeField;
            }
            set {
                this.node_typeField = value;
            }
        }
        
        /// <remarks/>
        public basic_type basic_type {
            get {
                return this.basic_typeField;
            }
            set {
                this.basic_typeField = value;
            }
        }
        
        /// <remarks/>
        public access access {
            get {
                return this.accessField;
            }
            set {
                this.accessField = value;
            }
        }
        
        /// <remarks/>
        public kind kind {
            get {
                return this.kindField;
            }
            set {
                this.kindField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XMLSchemaOpcUa.xsd")]
    public partial class node_id {
        
        private ushort namespace_indexField;
        
        private string idField;
        
        public node_id() {
            this.namespace_indexField = ((ushort)(1));
        }
        
        /// <remarks/>
        public ushort namespace_index {
            get {
                return this.namespace_indexField;
            }
            set {
                this.namespace_indexField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XMLSchemaOpcUa.xsd")]
    public partial class folder {
        
        private node_type node_typeField;
        
        private string nameField;
        
        private node_id node_idField;
        
        public folder() {
            this.node_typeField = node_type.Folder;
        }
        
        /// <remarks/>
        public node_type node_type {
            get {
                return this.node_typeField;
            }
            set {
                this.node_typeField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public node_id node_id {
            get {
                return this.node_idField;
            }
            set {
                this.node_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XMLSchemaOpcUa.xsd")]
    public partial class @namespace {
        
        private node_type node_typeField;
        
        private ushort indexField;
        
        public @namespace() {
            this.node_typeField = node_type.Namespace;
        }
        
        /// <remarks/>
        public node_type node_type {
            get {
                return this.node_typeField;
            }
            set {
                this.node_typeField = value;
            }
        }
        
        /// <remarks/>
        public ushort index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
    }
}
