//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
namespace ConfigOpcUaNet {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ConfigOpcUa.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("OpcConfiguration", Namespace="http://tempuri.org/ConfigOpcUa.xsd", IsNullable=false)]
    public partial class opcConfigurationType {
        
        private string localIpAddressField;
        
        private string groupIpAddressField;
        
        private objectType[] objectsField;
        
        /// <remarks/>
        public string LocalIpAddress {
            get {
                return this.localIpAddressField;
            }
            set {
                this.localIpAddressField = value;
            }
        }
        
        /// <remarks/>
        public string GroupIpAddress {
            get {
                return this.groupIpAddressField;
            }
            set {
                this.groupIpAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Objects")]
        public objectType[] Objects {
            get {
                return this.objectsField;
            }
            set {
                this.objectsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ConfigOpcUa.xsd")]
    public partial class objectType {
        
        private objectItemType[] itemsField;
        
        private string nameField;
        
        private ushort publishingIntervalField;
        
        private bool publishingIntervalFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items")]
        public objectItemType[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort PublishingInterval {
            get {
                return this.publishingIntervalField;
            }
            set {
                this.publishingIntervalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PublishingIntervalSpecified {
            get {
                return this.publishingIntervalFieldSpecified;
            }
            set {
                this.publishingIntervalFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ConfigOpcUa.xsd")]
    public partial class objectItemType {
        
        private string nameField;
        
        private string basicTypeField;
        
        private string accessField;
        
        private string rankField;
        
        private ushort arraySizeField;
        
        private bool arraySizeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BasicType {
            get {
                return this.basicTypeField;
            }
            set {
                this.basicTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Access {
            get {
                return this.accessField;
            }
            set {
                this.accessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort ArraySize {
            get {
                return this.arraySizeField;
            }
            set {
                this.arraySizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ArraySizeSpecified {
            get {
                return this.arraySizeFieldSpecified;
            }
            set {
                this.arraySizeFieldSpecified = value;
            }
        }
    }
}
