//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
namespace ConfigOpcUaNet {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ConfigOpcUa.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ConfigOpcUa.xsd", IsNullable=false)]
    public partial class OpcConfiguration {
        
        private string localIpAddressField;
        
        private string groupIpAddressField;
        
        private OpcConfigurationObject[] objectsField;
        
        /// <remarks/>
        public string LocalIpAddress {
            get {
                return this.localIpAddressField;
            }
            set {
                this.localIpAddressField = value;
            }
        }
        
        /// <remarks/>
        public string GroupIpAddress {
            get {
                return this.groupIpAddressField;
            }
            set {
                this.groupIpAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Object", IsNullable=false)]
        public OpcConfigurationObject[] Objects {
            get {
                return this.objectsField;
            }
            set {
                this.objectsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ConfigOpcUa.xsd")]
    public partial class OpcConfigurationObject {
        
        private OpcConfigurationObjectItem[] itemsField;
        
        private string nameField;
        
        private ushort publishingIntervalField;
        
        private bool publishingIntervalFieldSpecified;
        
        private bool pubField;
        
        private bool pubFieldSpecified;
        
        private bool subField;
        
        private bool subFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable=false)]
        public OpcConfigurationObjectItem[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort PublishingInterval {
            get {
                return this.publishingIntervalField;
            }
            set {
                this.publishingIntervalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PublishingIntervalSpecified {
            get {
                return this.publishingIntervalFieldSpecified;
            }
            set {
                this.publishingIntervalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Pub {
            get {
                return this.pubField;
            }
            set {
                this.pubField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PubSpecified {
            get {
                return this.pubFieldSpecified;
            }
            set {
                this.pubFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Sub {
            get {
                return this.subField;
            }
            set {
                this.subField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubSpecified {
            get {
                return this.subFieldSpecified;
            }
            set {
                this.subFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ConfigOpcUa.xsd")]
    public partial class OpcConfigurationObjectItem {
        
        private string nameField;
        
        private string basicTypeField;
        
        private string accessField;
        
        private string rankField;
        
        private ushort arraySizeField;
        
        private bool arraySizeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BasicType {
            get {
                return this.basicTypeField;
            }
            set {
                this.basicTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Access {
            get {
                return this.accessField;
            }
            set {
                this.accessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort ArraySize {
            get {
                return this.arraySizeField;
            }
            set {
                this.arraySizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ArraySizeSpecified {
            get {
                return this.arraySizeFieldSpecified;
            }
            set {
                this.arraySizeFieldSpecified = value;
            }
        }
    }
}
